#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NetApp.Resource", IsApplication=true)]

namespace NetApp
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Essentials.Resource.Attribute.alpha = global::NetApp.Resource.Attribute.alpha;
			global::Xamarin.Essentials.Resource.Attribute.coordinatorLayoutStyle = global::NetApp.Resource.Attribute.coordinatorLayoutStyle;
			global::Xamarin.Essentials.Resource.Attribute.font = global::NetApp.Resource.Attribute.font;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderAuthority = global::NetApp.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderCerts = global::NetApp.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchStrategy = global::NetApp.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderFetchTimeout = global::NetApp.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderPackage = global::NetApp.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Essentials.Resource.Attribute.fontProviderQuery = global::NetApp.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Essentials.Resource.Attribute.fontStyle = global::NetApp.Resource.Attribute.fontStyle;
			global::Xamarin.Essentials.Resource.Attribute.fontVariationSettings = global::NetApp.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Essentials.Resource.Attribute.fontWeight = global::NetApp.Resource.Attribute.fontWeight;
			global::Xamarin.Essentials.Resource.Attribute.keylines = global::NetApp.Resource.Attribute.keylines;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchor = global::NetApp.Resource.Attribute.layout_anchor;
			global::Xamarin.Essentials.Resource.Attribute.layout_anchorGravity = global::NetApp.Resource.Attribute.layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Attribute.layout_behavior = global::NetApp.Resource.Attribute.layout_behavior;
			global::Xamarin.Essentials.Resource.Attribute.layout_dodgeInsetEdges = global::NetApp.Resource.Attribute.layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Attribute.layout_insetEdge = global::NetApp.Resource.Attribute.layout_insetEdge;
			global::Xamarin.Essentials.Resource.Attribute.layout_keyline = global::NetApp.Resource.Attribute.layout_keyline;
			global::Xamarin.Essentials.Resource.Attribute.statusBarBackground = global::NetApp.Resource.Attribute.statusBarBackground;
			global::Xamarin.Essentials.Resource.Attribute.ttcIndex = global::NetApp.Resource.Attribute.ttcIndex;
			global::Xamarin.Essentials.Resource.Color.browser_actions_bg_grey = global::NetApp.Resource.Color.browser_actions_bg_grey;
			global::Xamarin.Essentials.Resource.Color.browser_actions_divider_color = global::NetApp.Resource.Color.browser_actions_divider_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_text_color = global::NetApp.Resource.Color.browser_actions_text_color;
			global::Xamarin.Essentials.Resource.Color.browser_actions_title_color = global::NetApp.Resource.Color.browser_actions_title_color;
			global::Xamarin.Essentials.Resource.Color.notification_action_color_filter = global::NetApp.Resource.Color.notification_action_color_filter;
			global::Xamarin.Essentials.Resource.Color.notification_icon_bg_color = global::NetApp.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Essentials.Resource.Color.ripple_material_light = global::NetApp.Resource.Color.ripple_material_light;
			global::Xamarin.Essentials.Resource.Color.secondary_text_default_material_light = global::NetApp.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_max_width = global::NetApp.Resource.Dimension.browser_actions_context_menu_max_width;
			global::Xamarin.Essentials.Resource.Dimension.browser_actions_context_menu_min_padding = global::NetApp.Resource.Dimension.browser_actions_context_menu_min_padding;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_horizontal_material = global::NetApp.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_inset_vertical_material = global::NetApp.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_horizontal_material = global::NetApp.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_button_padding_vertical_material = global::NetApp.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_control_corner_material = global::NetApp.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_height = global::NetApp.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Essentials.Resource.Dimension.compat_notification_large_icon_max_width = global::NetApp.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_icon_size = global::NetApp.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_action_text_size = global::NetApp.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_big_circle_margin = global::NetApp.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_content_margin_start = global::NetApp.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_height = global::NetApp.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Essentials.Resource.Dimension.notification_large_icon_width = global::NetApp.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Essentials.Resource.Dimension.notification_main_column_padding_top = global::NetApp.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_media_narrow_margin = global::NetApp.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_icon_size = global::NetApp.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_right_side_padding_top = global::NetApp.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_background_padding = global::NetApp.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Essentials.Resource.Dimension.notification_small_icon_size_as_large = global::NetApp.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Essentials.Resource.Dimension.notification_subtext_size = global::NetApp.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad = global::NetApp.Resource.Dimension.notification_top_pad;
			global::Xamarin.Essentials.Resource.Dimension.notification_top_pad_large_text = global::NetApp.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Essentials.Resource.Drawable.notification_action_background = global::NetApp.Resource.Drawable.notification_action_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg = global::NetApp.Resource.Drawable.notification_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low = global::NetApp.Resource.Drawable.notification_bg_low;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_normal = global::NetApp.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_low_pressed = global::NetApp.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal = global::NetApp.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Essentials.Resource.Drawable.notification_bg_normal_pressed = global::NetApp.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Essentials.Resource.Drawable.notification_icon_background = global::NetApp.Resource.Drawable.notification_icon_background;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_bg = global::NetApp.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_template_icon_low_bg = global::NetApp.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Essentials.Resource.Drawable.notification_tile_bg = global::NetApp.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Essentials.Resource.Drawable.notify_panel_notification_icon_bg = global::NetApp.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Essentials.Resource.Id.accessibility_action_clickable_span = global::NetApp.Resource.Id.accessibility_action_clickable_span;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_0 = global::NetApp.Resource.Id.accessibility_custom_action_0;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_1 = global::NetApp.Resource.Id.accessibility_custom_action_1;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_10 = global::NetApp.Resource.Id.accessibility_custom_action_10;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_11 = global::NetApp.Resource.Id.accessibility_custom_action_11;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_12 = global::NetApp.Resource.Id.accessibility_custom_action_12;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_13 = global::NetApp.Resource.Id.accessibility_custom_action_13;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_14 = global::NetApp.Resource.Id.accessibility_custom_action_14;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_15 = global::NetApp.Resource.Id.accessibility_custom_action_15;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_16 = global::NetApp.Resource.Id.accessibility_custom_action_16;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_17 = global::NetApp.Resource.Id.accessibility_custom_action_17;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_18 = global::NetApp.Resource.Id.accessibility_custom_action_18;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_19 = global::NetApp.Resource.Id.accessibility_custom_action_19;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_2 = global::NetApp.Resource.Id.accessibility_custom_action_2;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_20 = global::NetApp.Resource.Id.accessibility_custom_action_20;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_21 = global::NetApp.Resource.Id.accessibility_custom_action_21;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_22 = global::NetApp.Resource.Id.accessibility_custom_action_22;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_23 = global::NetApp.Resource.Id.accessibility_custom_action_23;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_24 = global::NetApp.Resource.Id.accessibility_custom_action_24;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_25 = global::NetApp.Resource.Id.accessibility_custom_action_25;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_26 = global::NetApp.Resource.Id.accessibility_custom_action_26;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_27 = global::NetApp.Resource.Id.accessibility_custom_action_27;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_28 = global::NetApp.Resource.Id.accessibility_custom_action_28;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_29 = global::NetApp.Resource.Id.accessibility_custom_action_29;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_3 = global::NetApp.Resource.Id.accessibility_custom_action_3;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_30 = global::NetApp.Resource.Id.accessibility_custom_action_30;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_31 = global::NetApp.Resource.Id.accessibility_custom_action_31;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_4 = global::NetApp.Resource.Id.accessibility_custom_action_4;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_5 = global::NetApp.Resource.Id.accessibility_custom_action_5;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_6 = global::NetApp.Resource.Id.accessibility_custom_action_6;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_7 = global::NetApp.Resource.Id.accessibility_custom_action_7;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_8 = global::NetApp.Resource.Id.accessibility_custom_action_8;
			global::Xamarin.Essentials.Resource.Id.accessibility_custom_action_9 = global::NetApp.Resource.Id.accessibility_custom_action_9;
			global::Xamarin.Essentials.Resource.Id.actions = global::NetApp.Resource.Id.actions;
			global::Xamarin.Essentials.Resource.Id.action_container = global::NetApp.Resource.Id.action_container;
			global::Xamarin.Essentials.Resource.Id.action_divider = global::NetApp.Resource.Id.action_divider;
			global::Xamarin.Essentials.Resource.Id.action_image = global::NetApp.Resource.Id.action_image;
			global::Xamarin.Essentials.Resource.Id.action_text = global::NetApp.Resource.Id.action_text;
			global::Xamarin.Essentials.Resource.Id.all = global::NetApp.Resource.Id.all;
			global::Xamarin.Essentials.Resource.Id.async = global::NetApp.Resource.Id.async;
			global::Xamarin.Essentials.Resource.Id.blocking = global::NetApp.Resource.Id.blocking;
			global::Xamarin.Essentials.Resource.Id.bottom = global::NetApp.Resource.Id.bottom;
			global::Xamarin.Essentials.Resource.Id.browser_actions_header_text = global::NetApp.Resource.Id.browser_actions_header_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_items = global::NetApp.Resource.Id.browser_actions_menu_items;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_icon = global::NetApp.Resource.Id.browser_actions_menu_item_icon;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_item_text = global::NetApp.Resource.Id.browser_actions_menu_item_text;
			global::Xamarin.Essentials.Resource.Id.browser_actions_menu_view = global::NetApp.Resource.Id.browser_actions_menu_view;
			global::Xamarin.Essentials.Resource.Id.center = global::NetApp.Resource.Id.center;
			global::Xamarin.Essentials.Resource.Id.center_horizontal = global::NetApp.Resource.Id.center_horizontal;
			global::Xamarin.Essentials.Resource.Id.center_vertical = global::NetApp.Resource.Id.center_vertical;
			global::Xamarin.Essentials.Resource.Id.chronometer = global::NetApp.Resource.Id.chronometer;
			global::Xamarin.Essentials.Resource.Id.clip_horizontal = global::NetApp.Resource.Id.clip_horizontal;
			global::Xamarin.Essentials.Resource.Id.clip_vertical = global::NetApp.Resource.Id.clip_vertical;
			global::Xamarin.Essentials.Resource.Id.dialog_button = global::NetApp.Resource.Id.dialog_button;
			global::Xamarin.Essentials.Resource.Id.end = global::NetApp.Resource.Id.end;
			global::Xamarin.Essentials.Resource.Id.fill = global::NetApp.Resource.Id.fill;
			global::Xamarin.Essentials.Resource.Id.fill_horizontal = global::NetApp.Resource.Id.fill_horizontal;
			global::Xamarin.Essentials.Resource.Id.fill_vertical = global::NetApp.Resource.Id.fill_vertical;
			global::Xamarin.Essentials.Resource.Id.forever = global::NetApp.Resource.Id.forever;
			global::Xamarin.Essentials.Resource.Id.icon = global::NetApp.Resource.Id.icon;
			global::Xamarin.Essentials.Resource.Id.icon_group = global::NetApp.Resource.Id.icon_group;
			global::Xamarin.Essentials.Resource.Id.info = global::NetApp.Resource.Id.info;
			global::Xamarin.Essentials.Resource.Id.italic = global::NetApp.Resource.Id.italic;
			global::Xamarin.Essentials.Resource.Id.left = global::NetApp.Resource.Id.left;
			global::Xamarin.Essentials.Resource.Id.line1 = global::NetApp.Resource.Id.line1;
			global::Xamarin.Essentials.Resource.Id.line3 = global::NetApp.Resource.Id.line3;
			global::Xamarin.Essentials.Resource.Id.none = global::NetApp.Resource.Id.none;
			global::Xamarin.Essentials.Resource.Id.normal = global::NetApp.Resource.Id.normal;
			global::Xamarin.Essentials.Resource.Id.notification_background = global::NetApp.Resource.Id.notification_background;
			global::Xamarin.Essentials.Resource.Id.notification_main_column = global::NetApp.Resource.Id.notification_main_column;
			global::Xamarin.Essentials.Resource.Id.notification_main_column_container = global::NetApp.Resource.Id.notification_main_column_container;
			global::Xamarin.Essentials.Resource.Id.right = global::NetApp.Resource.Id.right;
			global::Xamarin.Essentials.Resource.Id.right_icon = global::NetApp.Resource.Id.right_icon;
			global::Xamarin.Essentials.Resource.Id.right_side = global::NetApp.Resource.Id.right_side;
			global::Xamarin.Essentials.Resource.Id.start = global::NetApp.Resource.Id.start;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_actions = global::NetApp.Resource.Id.tag_accessibility_actions;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_clickable_spans = global::NetApp.Resource.Id.tag_accessibility_clickable_spans;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_heading = global::NetApp.Resource.Id.tag_accessibility_heading;
			global::Xamarin.Essentials.Resource.Id.tag_accessibility_pane_title = global::NetApp.Resource.Id.tag_accessibility_pane_title;
			global::Xamarin.Essentials.Resource.Id.tag_screen_reader_focusable = global::NetApp.Resource.Id.tag_screen_reader_focusable;
			global::Xamarin.Essentials.Resource.Id.tag_transition_group = global::NetApp.Resource.Id.tag_transition_group;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_event_manager = global::NetApp.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Essentials.Resource.Id.tag_unhandled_key_listeners = global::NetApp.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Essentials.Resource.Id.text = global::NetApp.Resource.Id.text;
			global::Xamarin.Essentials.Resource.Id.text2 = global::NetApp.Resource.Id.text2;
			global::Xamarin.Essentials.Resource.Id.time = global::NetApp.Resource.Id.time;
			global::Xamarin.Essentials.Resource.Id.title = global::NetApp.Resource.Id.title;
			global::Xamarin.Essentials.Resource.Id.top = global::NetApp.Resource.Id.top;
			global::Xamarin.Essentials.Resource.Integer.status_bar_notification_info_maxnum = global::NetApp.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_page = global::NetApp.Resource.Layout.browser_actions_context_menu_page;
			global::Xamarin.Essentials.Resource.Layout.browser_actions_context_menu_row = global::NetApp.Resource.Layout.browser_actions_context_menu_row;
			global::Xamarin.Essentials.Resource.Layout.custom_dialog = global::NetApp.Resource.Layout.custom_dialog;
			global::Xamarin.Essentials.Resource.Layout.notification_action = global::NetApp.Resource.Layout.notification_action;
			global::Xamarin.Essentials.Resource.Layout.notification_action_tombstone = global::NetApp.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Essentials.Resource.Layout.notification_template_custom_big = global::NetApp.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Essentials.Resource.Layout.notification_template_icon_group = global::NetApp.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_chronometer = global::NetApp.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Essentials.Resource.Layout.notification_template_part_time = global::NetApp.Resource.Layout.notification_template_part_time;
			global::Xamarin.Essentials.Resource.String.status_bar_notification_info_overflow = global::NetApp.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification = global::NetApp.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Info = global::NetApp.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::NetApp.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Time = global::NetApp.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Essentials.Resource.Style.TextAppearance_Compat_Notification_Title = global::NetApp.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionContainer = global::NetApp.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Essentials.Resource.Style.Widget_Compat_NotificationActionText = global::NetApp.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Essentials.Resource.Style.Widget_Support_CoordinatorLayout = global::NetApp.Resource.Style.Widget_Support_CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem = global::NetApp.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_alpha = global::NetApp.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_alpha = global::NetApp.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Essentials.Resource.Styleable.ColorStateListItem_android_color = global::NetApp.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout = global::NetApp.Resource.Styleable.CoordinatorLayout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_keylines = global::NetApp.Resource.Styleable.CoordinatorLayout_keylines;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout = global::NetApp.Resource.Styleable.CoordinatorLayout_Layout;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::NetApp.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::NetApp.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::NetApp.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::NetApp.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::NetApp.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::NetApp.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::NetApp.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::Xamarin.Essentials.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::NetApp.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily = global::NetApp.Resource.Styleable.FontFamily;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont = global::NetApp.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_font = global::NetApp.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontStyle = global::NetApp.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::NetApp.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_fontWeight = global::NetApp.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::NetApp.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_font = global::NetApp.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontStyle = global::NetApp.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::NetApp.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_fontWeight = global::NetApp.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Essentials.Resource.Styleable.FontFamilyFont_ttcIndex = global::NetApp.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderAuthority = global::NetApp.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderCerts = global::NetApp.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::NetApp.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::NetApp.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderPackage = global::NetApp.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Essentials.Resource.Styleable.FontFamily_fontProviderQuery = global::NetApp.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor = global::NetApp.Resource.Styleable.GradientColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem = global::NetApp.Resource.Styleable.GradientColorItem;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_color = global::NetApp.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Essentials.Resource.Styleable.GradientColorItem_android_offset = global::NetApp.Resource.Styleable.GradientColorItem_android_offset;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerColor = global::NetApp.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerX = global::NetApp.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_centerY = global::NetApp.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endColor = global::NetApp.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endX = global::NetApp.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_endY = global::NetApp.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_gradientRadius = global::NetApp.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startColor = global::NetApp.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startX = global::NetApp.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_startY = global::NetApp.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_tileMode = global::NetApp.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Essentials.Resource.Styleable.GradientColor_android_type = global::NetApp.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::NetApp.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int alpha = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int coordinatorLayoutStyle = 2130771968;
			
			// aapt resource value: 0x7f010011
			public const int font = 2130771985;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderAuthority = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderCerts = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchStrategy = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderFetchTimeout = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderPackage = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderQuery = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int fontStyle = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int fontVariationSettings = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int fontWeight = 2130771986;
			
			// aapt resource value: 0x7f010001
			public const int keylines = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int layout_anchor = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int layout_anchorGravity = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int layout_behavior = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int layout_dodgeInsetEdges = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int layout_insetEdge = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int layout_keyline = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int statusBarBackground = 2130771970;
			
			// aapt resource value: 0x7f010014
			public const int ttcIndex = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int browser_actions_bg_grey = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int browser_actions_divider_color = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int browser_actions_text_color = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int browser_actions_title_color = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int colorAccent = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int colorPrimary = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int colorPrimaryDark = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int ic_launcher_background = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int notification_action_color_filter = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int notification_icon_bg_color = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int ripple_material_light = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int secondary_text_default_material_light = 2131099655;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int browser_actions_context_menu_max_width = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int browser_actions_context_menu_min_padding = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int compat_button_inset_horizontal_material = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int compat_button_inset_vertical_material = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int compat_button_padding_horizontal_material = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int compat_button_padding_vertical_material = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int compat_control_corner_material = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int compat_notification_large_icon_max_height = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int compat_notification_large_icon_max_width = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int notification_action_icon_size = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int notification_action_text_size = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int notification_big_circle_margin = 2131165199;
			
			// aapt resource value: 0x7f070003
			public const int notification_content_margin_start = 2131165187;
			
			// aapt resource value: 0x7f070010
			public const int notification_large_icon_height = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int notification_large_icon_width = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int notification_main_column_padding_top = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int notification_media_narrow_margin = 2131165189;
			
			// aapt resource value: 0x7f070012
			public const int notification_right_icon_size = 2131165202;
			
			// aapt resource value: 0x7f070002
			public const int notification_right_side_padding_top = 2131165186;
			
			// aapt resource value: 0x7f070013
			public const int notification_small_icon_background_padding = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int notification_small_icon_size_as_large = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int notification_subtext_size = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int notification_top_pad = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int notification_top_pad_large_text = 2131165207;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Error = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int images = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Internet = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int NetIco = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int NoConnectivity = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_action_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_bg_low = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notification_bg_low_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int notification_bg_low_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_bg_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int notification_bg_normal_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_icon_background = 2130837517;
			
			// aapt resource value: 0x7f020015
			public const int notification_template_icon_bg = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int notification_template_icon_low_bg = 2130837526;
			
			// aapt resource value: 0x7f02000e
			public const int notification_tile_bg = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int notify_panel_notification_icon_bg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Splash = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Splash2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Splash3 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Splash4 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Splash5 = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int accessibility_action_clickable_span = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int accessibility_custom_action_0 = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int accessibility_custom_action_1 = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int accessibility_custom_action_10 = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int accessibility_custom_action_11 = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int accessibility_custom_action_12 = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int accessibility_custom_action_13 = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int accessibility_custom_action_14 = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int accessibility_custom_action_15 = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int accessibility_custom_action_16 = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int accessibility_custom_action_17 = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int accessibility_custom_action_18 = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int accessibility_custom_action_19 = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int accessibility_custom_action_2 = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int accessibility_custom_action_20 = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int accessibility_custom_action_21 = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int accessibility_custom_action_22 = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int accessibility_custom_action_23 = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int accessibility_custom_action_24 = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int accessibility_custom_action_25 = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int accessibility_custom_action_26 = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int accessibility_custom_action_27 = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int accessibility_custom_action_28 = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int accessibility_custom_action_29 = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int accessibility_custom_action_3 = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int accessibility_custom_action_30 = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int accessibility_custom_action_31 = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int accessibility_custom_action_4 = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int accessibility_custom_action_5 = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int accessibility_custom_action_6 = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int accessibility_custom_action_7 = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int accessibility_custom_action_8 = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int accessibility_custom_action_9 = 2131361824;
			
			// aapt resource value: 0x7f0a004b
			public const int action_container = 2131361867;
			
			// aapt resource value: 0x7f0a0057
			public const int action_divider = 2131361879;
			
			// aapt resource value: 0x7f0a004c
			public const int action_image = 2131361868;
			
			// aapt resource value: 0x7f0a004d
			public const int action_text = 2131361869;
			
			// aapt resource value: 0x7f0a0058
			public const int actions = 2131361880;
			
			// aapt resource value: 0x7f0a003d
			public const int all = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public const int async = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public const int blocking = 2131361855;
			
			// aapt resource value: 0x7f0a002e
			public const int bottom = 2131361838;
			
			// aapt resource value: 0x7f0a0045
			public const int browser_actions_header_text = 2131361861;
			
			// aapt resource value: 0x7f0a0047
			public const int browser_actions_menu_item_icon = 2131361863;
			
			// aapt resource value: 0x7f0a0048
			public const int browser_actions_menu_item_text = 2131361864;
			
			// aapt resource value: 0x7f0a0046
			public const int browser_actions_menu_items = 2131361862;
			
			// aapt resource value: 0x7f0a0044
			public const int browser_actions_menu_view = 2131361860;
			
			// aapt resource value: 0x7f0a002f
			public const int center = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int center_horizontal = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int center_vertical = 2131361841;
			
			// aapt resource value: 0x7f0a0056
			public const int chronometer = 2131361878;
			
			// aapt resource value: 0x7f0a0032
			public const int clip_horizontal = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int clip_vertical = 2131361843;
			
			// aapt resource value: 0x7f0a0049
			public const int dialog_button = 2131361865;
			
			// aapt resource value: 0x7f0a0034
			public const int end = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int fill = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int fill_horizontal = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int fill_vertical = 2131361847;
			
			// aapt resource value: 0x7f0a0040
			public const int forever = 2131361856;
			
			// aapt resource value: 0x7f0a004f
			public const int icon = 2131361871;
			
			// aapt resource value: 0x7f0a0059
			public const int icon_group = 2131361881;
			
			// aapt resource value: 0x7f0a0043
			public const int imageView = 2131361859;
			
			// aapt resource value: 0x7f0a0052
			public const int info = 2131361874;
			
			// aapt resource value: 0x7f0a0041
			public const int italic = 2131361857;
			
			// aapt resource value: 0x7f0a0038
			public const int left = 2131361848;
			
			// aapt resource value: 0x7f0a0021
			public const int line1 = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int line3 = 2131361826;
			
			// aapt resource value: 0x7f0a003c
			public const int none = 2131361852;
			
			// aapt resource value: 0x7f0a0042
			public const int normal = 2131361858;
			
			// aapt resource value: 0x7f0a0054
			public const int notification_background = 2131361876;
			
			// aapt resource value: 0x7f0a0050
			public const int notification_main_column = 2131361872;
			
			// aapt resource value: 0x7f0a004e
			public const int notification_main_column_container = 2131361870;
			
			// aapt resource value: 0x7f0a0039
			public const int right = 2131361849;
			
			// aapt resource value: 0x7f0a0053
			public const int right_icon = 2131361875;
			
			// aapt resource value: 0x7f0a0051
			public const int right_side = 2131361873;
			
			// aapt resource value: 0x7f0a003a
			public const int start = 2131361850;
			
			// aapt resource value: 0x7f0a0023
			public const int tag_accessibility_actions = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int tag_accessibility_clickable_spans = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int tag_accessibility_heading = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int tag_accessibility_pane_title = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public const int tag_screen_reader_focusable = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int tag_transition_group = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int tag_unhandled_key_event_manager = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int tag_unhandled_key_listeners = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int text = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public const int text2 = 2131361836;
			
			// aapt resource value: 0x7f0a0055
			public const int time = 2131361877;
			
			// aapt resource value: 0x7f0a002d
			public const int title = 2131361837;
			
			// aapt resource value: 0x7f0a003b
			public const int top = 2131361851;
			
			// aapt resource value: 0x7f0a004a
			public const int webView1 = 2131361866;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0b0000
			public const int status_bar_notification_info_maxnum = 2131427328;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int browser_actions_context_menu_page = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int browser_actions_context_menu_row = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int custom_dialog = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Main = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_action = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_action_tombstone = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int notification_template_custom_big = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int notification_template_icon_group = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int notification_template_part_chronometer = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int notification_template_part_time = 2130968586;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_launcher_foreground = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_launcher_round = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090002
			public const int action_settings = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int status_bar_notification_info_overflow = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Info = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int TextAppearance_Compat_Notification_Line2 = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Time = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int TextAppearance_Compat_Notification_Title = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int Theme_Splash = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int Widget_Compat_NotificationActionContainer = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int Widget_Compat_NotificationActionText = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int Widget_Support_CoordinatorLayout = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int xamarin_essentials_fileprovider_file_paths = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771977};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			public static int[] CoordinatorLayout = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchor = 2;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 4;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_behavior = 1;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 6;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_keyline = 3;
			
			public static int[] FontFamily = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 6
			public const int FontFamilyFont_font = 6;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontStyle = 5;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontVariationSettings = 8;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontWeight = 7;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
